name: note_app_server
description: A server app using the shelf package and Docker.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.0

dependencies:
  args: ^2.4.0
  dotenv: ^4.2.0
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  supabase: ^2.2.7
  jwt_decoder: ^2.0.1

dev_dependencies:
  http: ^1.1.0
  lints: ^2.1.0
  test: ^1.24.0

assets:
  - .env
